### ISSUE TITLE
Working Github actions starts failing now with AttributeError, error in MainThread

### ISSUE THREAD

**Issue by rahulsarchive** [DoomHammer/roam-to-git#5]
**Describe the bug**
I was using the workflow for about 3 weeks, but suddenly from 3 days back, all the jobs have been failing. They have the same error. I tried resetting the GitHub secrets but does not work.
**To Reproduce**
Don't know what happened, I did not change any settings before the jobs started failing.

**Traceback**

Run roam-to-git --skip-fetch --skip-git .
  roam-to-git --skip-fetch --skip-git .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.11/x64
    ROAMRESEARCH_USER: ***
    ROAMRESEARCH_PASSWORD: ***
    ROAMRESEARCH_DATABASE: ***
2021-08-18 17:16:35.729 | ERROR    | __main__:<module>:33 - An error has been caught in function '<module>', process 'MainProcess' (1912), thread 'MainThread' (139748815165248):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.11/x64/bin/roam-to-git", line 33, in <module>
    sys.exit(load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')())
    │   │    └ <function importlib_load_entry_point at 0x7f19ce30d4c0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
    patch_pyppeteer()
    └ <function patch_pyppeteer at 0x7f19cd4823a0>
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 18, in patch_pyppeteer
    original_method = pyppeteer.connection.websockets.client.connect
                      │         │          └ <module 'websockets' from '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/websockets/__init__.py'>
                      │         └ <module 'pyppeteer.connection' from '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pyppeteer/connection....
                      └ <module 'pyppeteer' from '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pyppeteer/__init__.py'>
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/websockets/imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")

AttributeError: module 'websockets' has no attribute 'client'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/bin/roam-to-git", line 33, in <module>
    sys.exit(load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')())
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1149, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
    patch_pyppeteer()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 18, in patch_pyppeteer
    original_method = pyppeteer.connection.websockets.client.connect
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/websockets/imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
Error: Process completed with exit code 1.

**Run `roam-to-git --debug notes/` and report what you get.**
Don't know how to run this, where should I run the command?

**Please complete the following information:**
- OS: [Win 10]
- Do you use Github Action? Yes
- Do you use multiple Roam databases? only one
- Does roam-to-git use to work for you? When precisely did it stopped to work?  was working for 3 weeks, stopped on 16 Aug 2021
- Does some backup runs are still working? No

**Additional context**

**Comment by alaq** [comment]
You're not the only one. I'm experiencing the same issue.

**Comment by alaq** [comment]
https://github.com/DoomHammer/roam-to-git/commit/b84091c4d8cbb5108eacd2eb53f105b45f3d7560 should fix it @rahulsarchive

**Comment by rahulsarchive** [comment]
Yes, thank you for the help, it works now.
